apiVersion: v1
kind: Service
metadata:
  name: portfolio-calculator
  namespace: production
  labels:
    app: portfolio-calculator
spec:
  type: ClusterIP
  selector:
    app: portfolio-calculator
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP