apiVersion: v1
kind: ServiceAccount
metadata:
  name: market-data-sa
  namespace: production
  annotations:
    # This annotation is how IRSA works
    # AWS SDK inside the pod sees this annotation
    # and automatically assumes this IAM role
    eks.amazonaws.com/role-arn: arn:aws:iam::882083662991:role/fintech-dev-market-data-role