kind : Service
apiVesrion: v1
metadata :
  name : market-data-ingestion
  namespace : production
  labels : 
    app: market-data-ingestion

spec: 
  type : ClusterIP
  selector :
    app: market-data-ingestion
  ports:
    - port : 80
      targetPort: 8080
      protocol : TCP
      